[[configs]]
datasets = ["sst5", "imdb"]
dataset_config_name = ["en"]
device = "cuda"
learning_rate = 0.3
model_name_or_path = "t5-base"
tokenizer_name_or_path = "t5-base"
max_target_length = 128
num_epochs = 0
batch_size = 32
peft_type = "attempt"
attn_method = "sub"
temperature = 2087
prompt_init = "embedding_multi"
prompt_init_embedding = "soft_prompts/origin_0/sst2.bin"
prompt_embedding_paths = ["soft_prompts/origin_0/sst2.bin", "soft_prompts/origin_0/yep_polarity.bin"]
prefix_num=2
task_type = "seq_2_seq_lm"
num_virtual_tokens = 50
n_runs = 1
wandb_project = "attempt_multi_sent"
max_source_length = 256
split_validation_test = true
max_train_samples = 0
max_valid_samples = 250
output_dir = "attempt_multi_sent"
warmup_steps = 500
shared_attn = true
pad_to_max_length = true